<?php
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath() . '/public');
}
echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Demo Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('font-awesome-4.1.0/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.js'));
        ?>

    </head>
    <script>
        //reset modal window data everytime it gets load
        $(document).on('hidden.bs.modal', function (e) {
			
            $(e.target).removeData('bs.modal');
        });
        function loginvalidation()
        {
			var email = $.trim($('#email').val());
			var password = $.trim($('#password').val());
            var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            var ch = 0;
            
            if (email == "")
            {
			    $('#email_error').html('Please enter an email.');
                $('#email_error').parent().addClass('error');
                ch++;
            }
            else if (!(regex.test(email))) {
                $('#email_error').html('Please enter an valid email.');
                $('#email_error').parent().addClass('error');
                ch++;
            }
            if (ch == 0) {
                $('#email_error').html('&nbsp;');
                $('#email_error').parent().removeClass('error');

            }
            if (password == "")
            {
                $('#password_error').html('Please enter a password.');
                $('#password_error').parent().addClass('error');
                ch++;
            }
            else {
                $('#password_error').html('&nbsp;');
                $('#password_error').parent().removeClass('error');

            }

            if (ch > 0)
            {
                return false;
            }
            else {
                return true;
            }
        }
//reset modal window data everytime it gets load
    $(document).on('hidden.bs.modal', function (e) {
        $('.modal-content').html('');
        //$(e.target).removeData('bs.modal');
    });
    </script>
    <body class="bt_login">
        <div class="container">
            <div class="row">
                <div id="myModal" class="modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">

                            <!-- Content will be loaded here from "remote.php" file -->
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-md-offset-3">
                    <div class="login-panel panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Login Admin <!--<img src="<?php echo $this->basePath('img/login_logo.png') ?>" class="pull-right">--></h3>
                        </div>
                        <div class="panel-body">
                            <div id="err_msg_id"><?php echo $this->flashMessenger()->render('error'); ?></div>
                            <div id="suceess_msg_id"><?php echo $this->flashMessenger()->render(); ?></div>
                            <?php
                            $form = $this->form;
                            $form->setAttributes(array('action' => $this->url(),
                                'onsubmit' => 'return loginvalidation();'));
                            $form->prepare();
                            echo $this->form()->openTag($form);
                            ?>
                            <div class="form-group">
                                <?php
                                $email = $form->get('email');
                                $email->setAttributes(array('class' => 'form-control',
                                    'placeholder' => 'E-mail', 'autofocus' => 'autofocus',
                                    'id' => 'email'));
                                echo $this->formInput($email);
                                ?>
                                <div class="error-message" id="email_error"></div>
                            </div>
                            <div class="form-group">
                                <?php
                                $password = $form->get('password');
                                $password->setAttributes(array('class' => 'form-control',
                                    'placeholder' => 'Password', 'id' => 'password'));
                                echo $this->formInput($password);
                                ?>
                                <div class="error-message" id="password_error"></div>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <?php echo $this->formRow($form->get('remember_me')); ?>Remember Me
                                </label>
                                <label class="pull-right">
                                    <a href="<?php echo $this->url('forgotPassword'); ?>" data-toggle="modal" data-target="#myModal"  data-backdrop="static">Forgot Password</a>
                                </label>
                            </div>
                            <?php
                            $submit = $form->get('submit');
                            $submit->setAttributes(array('class' => 'btn btn-lg btn-danger btn-block'));
                            echo $this->formInput($submit);
                            //echo $this->formCollection($form);
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>