<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					 View Product 
					 <div>
					 <?php echo $this->flashMessenger()->render('error'); ?>
					 </div>
				</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								<tr>
									<th>Product Name</th>
									<td><?php echo $product[0]['name'];?></td>
								</tr>
								<tr>
									<th>Product Price</th>
									<td><?php echo $product[0]['price'];?></td>
								</tr>
								<tr>
									<th>Product Quantity</th>
									<td><?php echo $product[0]['quantity'];?></td>
								</tr>
							</thead>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>