<div id="page-wrapper" >
	<div id="page-inner">
		<div class="row">
			<div class="col-md-12">
			 <h2>Users</h2>   
			</div>
		</div>
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					 Users
				</div>
				<div class="panel-body">
					<form action="<?php echo $this->url('userlist');?>" name="searchForm" id="searchForm" method="post">
						<table>
							<tr>
								<td>
								<input type="text" name="search" placeholder="Search">
								<input type="submit" name="submit" value="Search">
								</td>  
							</tr>
						</table>
					</form>
				</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								
								<tr>
									<th>First Name</th>
									<th>Username</th>
									<th>Email</th>
									<th>Mobile</th>
									<th>Country</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								<tr class="odd gradeX">
									<td>Anil</td>
									<td>Anilsingh</td>
									<td>anilsingh@gmail.com</td>
									<td class="center">9958407998</td>
									<td class="center">India</td>
									<td>
									    <a href="">Add</a>|
                                        <a href="">Edit</a>|									 
									    <a href="">Delete</a>|
										<a href="">View</a>
			                        </td>
								</tr>
								<tr class="even gradeC">
									<td>Lucky</td>
									<td>Luchysingh</td>
									<td>lucky@gmail.com</td>
									<td class="center">9999999999</td>
									<td class="center">India</td>
									<td>
									    <a href="">Add</a>|
                                        <a href="">Edit</a>|									 
									    <a href="">Delete</a>|
										<a href="">View</a>
			                        </td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="panel-body">
				
				</div>
			</div>
		</div>
	</div>
</div>