<div id="page-wrapper" >
	<div id="page-inner">
		<div class="row">
			<div class="col-md-12">
			 <h2>Users</h2>   
			</div>
		</div>
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					 Users
				</div>
				<div class="panel-body">
					<form action="<?php echo $this->url('userlist'); ?>" name="searchForm" id="searchForm" method="get">
						<table>
							<tr>
								<td>
								<input type="text" name="search" placeholder="Search" value="<?php echo @$_REQUEST['search']; ?>">
								<span><input type="submit" value="Search"></span>
								</td>  
							</tr>
						</table>
					</form>
				</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								
								<tr>
									<th>First Name</th>
									<th>Username</th>
									<th>Email</th>
									<th>Mobile</th>
									<th>Country</th>
									<th>Action</th>
								</tr>
							</thead>
							<?php foreach($rowset as $i=>$row){
								
								?>
							<tbody>
								<tr class="odd gradeX" >
									<td><?php  echo $row['first_name']; ?></td>
									<td><?php  echo $row['username']; ?></td>
									<td><?php  echo $row['email']; ?></td>
									<td class="center"><?php  echo $row['mob']; ?></td>
									<td class="center"><?php  echo $row['country']; ?></td>
									<td>
									    <a href="<?php echo $this->url('edituser',array('controller' => 'user', 'action' => 'edituser', 'id' => $row['id'])); ?>">Edit</a>|									 
									    <a href="<?php echo $this->url('deleteuser',array('controller'=>'user','action'=>'deleteuser','id'=>$row['id']));?>" onclick="return confirm('Do you want to delete this record?')">Delete</a>|
										<a href="<?php echo $this->url('viewuser',array('controller'=>'users','action'=>'viewuser','id'=>$row['id'])); ?>">View</a>
			                        </td>
								</tr>
							
								
							</tbody>
							<?php } ?>
						</table>
					</div>
				</div>
				
			</div>
		</div>
	</div>
</div>